### PR TITLE
Align font selection with operating system

### LINKED ISSUE #421: Report: Installation of "STIX Two Math" not working on Windows and Ubuntu
https://github.com/metanorma/metanorma-taste/actions/runs/21798848065/job/62890838426

STIX Two Math installs successfully on OSX, and fails on Windows and Ubuntu.

(The noisiness of the logs is not an excuse not to action this: the same errors are in in the OSX logs, but for the fact that STIX Two Math fails to install.)

This is blocking release, and pointing to inadequate font testing in Fontist.

### PR DESCRIPTION
**Pull request by suleman-uzair**
Ensures fonts are selected based on the user’s current operating system for improved consistency and appearance.

closes #421

### CODE REVIEW

File: lib/fontist/manifest.rb [hunk 1]
```diff
@@ -79,16 +79,22 @@ def validate_location_parameter!(location)
...
-      return if formula.nil?
-      return if formula.compatible_with_platform?
+      formula = Fontist::Formula.find_many(name)
+      return if formula.empty?
+      return if formula.any? { |f| supported_formula?(f) }
 
       raise Fontist::Errors::PlatformMismatchError.new(
         name,
-        formula.platforms,
+        formula.first.platforms,
```
Comment (HassanAkbar) [inline lib/fontist/manifest.rb]: I think we should use something like `formula.map(&:platforms).join(", ")`.
